[tool.poetry]
name = "chauvel-org"
version = "0.1.0"
description = "Jean-Pierre Chauvel's Blog"
authors = ["Jean-Pierre Chauvel <jean.p.chauvel@gmail.com>"]
license = "CC0"
readme = "README.md"
packages = [{include = "chauvel"}]

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
Sphinx = "^7.2.6"
myst-parser = {extras = ["linkify"], version = "^2.0.0"}
linkify = "^1.4"
pydata-sphinx-theme = "^0.15.2"
ablog = "^0.11.6"
sphinx-design = "^0.5.0"
sphinx-copybutton = "^0.5.2"
sphinx-togglebutton = "^0.3.2"
sphinxcontrib-youtube = "^1.4.1"
sphinx-sitemap = "^2.5.1"


[tool.poetry.group.dev.dependencies]
poetry-plugin-export = "^1.7.1"
black = "^24.3.0"

[tool.black]
line-length = 80

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
