name: Deploy chauvel.org to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Installe Build Tools
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential

      - name: Install dependencies
        run: |
          uv sync

      - name: Build blog
        run: |
          uv run ablog build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _website/
          exclude_assets: '.github'
          force_orphan: true
          cname: www.chauvel.org
